import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "./_components/Footer";
import NavbarWrapper from "./_components/navbar/NavbarWrapper";
import { WishlistDrawer } from "./_components/WishlistDrawer";
import { NotificationToast } from "./_components/NotificationToast";
import CartDrawerWrapper from "./_components/CartDrawerWrapper";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";
import { CartProvider } from "./_components/cart/cart-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anime Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = (await cookies()).get('cardId')?.value;
  const cart = getCart(cartId);
  console.log('cartId', cartId)
  console.log('cart', cart)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-background text-white selection:bg-neon-red/30">
      <CartProvider cartPromise={cart}>
        <NavbarWrapper/>
        <div className="relative z-10 pt-16 md:pt-24">
          {children}
          <Footer/>
        </div>
        {/* Global Overlay Drawers & Notifications */}
        <CartDrawerWrapper/>
        <WishlistDrawer/>
        <NotificationToast/>
        {/* <ProductDetails /> */}
      </CartProvider>

      </body>
    </html>
  );
}
